
name: Saleh Hamadeh's Website
markdown: redcarpet
highlighter: rouge
destination: _site/
permalink: /blog/:categories/:year/:month/:day/:title.html
description: Saleh Hamadeh's personal website. I write about technology, web development, and life in the bay area.
url: http://www.shamadeh.com